### ISSUE TITLE
Invalid argument Error

### ISSUE THREAD

**Issue by User9013** [Asd-g/AviSynth-DPID#1]
I have all the files that I think I need and run the function, but I get an error that the file cannot be loaded.
The error is "Platform returned code 126: Platform returned code 126: The specified module could not be found".
I would like to request support. Also, I would like to know if there are any other files needed besides Avsresize.

OS: Windows10
Version: Avisynth+ 3.70
CPU: Core-i5 10400F
GPU: Radeon RX580

**Comment by User9013** [comment]
After that, I managed to get rid of the 126 error message, but this time I got the "Invalid argument" error.
I searched for the DPID in AvsPmod, but it shows up with a strange icon.
The list of parameters also appears to be different from the one described (target_width and target_height are not present).
![none_](https://user-images.githubusercontent.com/65251154/132264337-0b1880f2-5364-44c7-99fe-9d0989e2922d.png)
![none](https://user-images.githubusercontent.com/65251154/132264338-f0616114-2457-46b0-b98e-ec28720ebbf8.png)

**Comment by Asd-g** [comment]
Avsresize is required only for DPID.
If Microsoft Visual C++ Redistributable Runtimes are missing, an error "there is no such function" (or something similar) will be returned. They can be downloaded from [here](https://github.com/abbodi1406/vcredist/releases).

For DPID required parameters are `clip input`, `int target_width`, `int target_height`. Usage example:
```
source
dpid(400, 200)
```
For DPIDraw required parameters are `clip input`, `clip input2`. Usage example:
```
source
dpidraw(z_Spline36Resize(400,200))
```
AvsPmod usually doesn't display the names of the mandatory parameters.
If you still have issues about the usage share the used script.

**Comment by User9013** [comment]
I installed the runtime package from the link you provided, and the error disappeared.
I had already installed some runtime packages, but it still didn't work at first, so I think you should specify in the README that you need to install the runtime package from the link you just provided.
Thank you very much!
